### ISSUE TITLE
공통 예외 처리 설정

### ISSUE THREAD

**Issue by jiyeoon00** [TogetherHana/Backend#1]
## 📌 Feature Issue

공통 예외 처리를 설정합니다.

## 📝 To-do

- [x] 커스텀 Exception (BaseException) 생성
- [x] ErrorType 정의
- [x] 응답할 response 정의
- [x] RestControllerAdvice 설정 및 BaseException 처리
