### ISSUE TITLE
모임통장 도메인 관련 기능 개발

### ISSUE THREAD

**Issue by iamcharles98** [TogetherHana/Backend#11]
## 📌 Feature Issue

[모임통장 도메인에 필요한 기능 개발]

## 📝 To-do

- [x] : 모임통장 개설 기능 구현
- [x] : 모임통장 계좌 이체 기능 구현
- [x] : 거래내역 조회 기능 구현
- [x] #18
- [ ] : 초대장 생성 기능 구현
- [ ] : 초대장 조회 기능 구현
- [x] : 모임통장 조회 기능 구현
- [x] : 모임통장 멤버 조회 기능 구현

**Comment by iamcharles98** [comment]
초대장 생성기능, 초대장 조회 기능은 push알림 브랜치에서 개발 예정
