### ISSUE TITLE
매치 승자처리 기능 구현

### ISSUE THREAD

**Issue by jiyeoon00** [TogetherHana/Backend#13]
## 📌 Feature Issue

승리호를 결정하는 기능을 구현합니다. 선택된 승리호 선원들을 모두 승리 처리합니다.

## 📝 To-do

- [x] 승리호 결정 시 게임 완료 처리 및 참여자들 승패 결정
- [x] 총무만 가능하도록 권한 처리
- [x] 패배자 정보 리턴
