### ISSUE TITLE
회원가입 및 로그인 기능 구현

### ISSUE THREAD

**Issue by lee010207** [TogetherHana/Backend#14]
## 📌 Feature Issue

회원가입 및 로그인 기능

## 📝 To-do

- [ ] 회원가입 API 구현
- [ ] JWT 인증 구현
- [ ] 로그인 API 구현
- [ ] 닉네임 중복검사 API 구현
