### ISSUE TITLE
회비걷기 요청 처리, 모임통장 초대 및 합류 기능 구현

### ISSUE THREAD

**Issue by iamcharles98** [TogetherHana/Backend#30]
## 📌 Feature Issue

1. 회비 걷기 요청 처리하기
2. 모임통장 초대장 생성기능
3. 모임통장 합류 기능

## 📝 To-do

- [x] : 회비걷기 푸시 알림 기능 구현
- [x] : 모임통장 초대장 생성 기능 구현(feat. Redis)
- [x] : 모임통장 합류 기능 구현(feat. Redis)
- [x] : 서비스에 가입되어 있는 유저인지 아닌지 확인하는 로직
