### ISSUE TITLE
승리팀 맞추기 이벤트 기능 구현

### ISSUE THREAD

**Issue by iamcharles98** [TogetherHana/Backend#35]
## 📌 Feature Issue

승리팀 맞추기 이벤트 기능 구현

## 📝 To-do

- [ ] : 경기 생성 api
- [ ] : 경기 조회 api
- [ ] : 경기 예측 및 경기를 위한 erd 설계
- [ ] : 경기 예측 api
- [ ] : 이벤트 종료 후 보상 기능 (스케쥴링)
- [ ] : 경기 별 참여자 수 확인
- [ ] : 전파된 총 마일리지 확인
