### ISSUE TITLE
auth 도메인 관련 기능 개발

### ISSUE THREAD

**Issue by iamcharles98** [TogetherHana/Backend#5]
## 📌 Feature Issue

[앱 본인인증 관련 기능을 개발합니다.]
- 본인인증(SMS) : 휴대폰으로 인증코드 문자를 전송해서 본인인증
- 계좌연동 : 계좌번호로 1원을 송금하여 인증숫자를 전송
- 인증숫자 확인 : 1원 송금 이체내역에 적힌 숫자를 확인
- 휴대폰코드 확인 : 본인의 휴대폰에 전송된 숫자를 확인
- 디바이스 인증 : 디바이스 토큰을 받아 JWT 토큰을 발행

## 📝 To-do

- [x] : SMS 인증 관련 의존성 추가
- [x] : SMS 인증 비즈니스 로직 개발
- [ ] : 계좌확인을 위한 사전거래 로직 개발
- [ ] : 1원인증을 위한 송금 로직개발
- [x] : SMS인증 코드, 1원 인증 코드 확인 로직 개발
- [x] : Redis 의존성 추가
- [ ] : 디바이스 인증 api 생성(JWT 연동 X)
